### ISSUE TITLE
Classify based on source code

### ISSUE THREAD

**Issue by Baschdl** [WGierke/git_better#30]
Classify repositories based on either
- name of files
- source code
   - one classifier per language
   - one classifier for all languages

## Tasks
- [x] clone repositories using "clone_url" in Github API response
- [x] merge source code files into one
   - [x] exclude binary files
   - [ ] limit size/number of merged files
- [ ] build interface to lazywei/mockingbird (GO or CLI)
or
- [x] use text classification approach
- [ ] play with some NNs
- [ ] distinguish between source code and comments

## Some links:
- [Deep Learning approach to Automatic Source Code Classification](https://github.com/github/linguist/issues/2618)
- [What's the code? Automatic Classification of Source Code Archives (kdd paper, 2002)](https://clgiles.ist.psu.edu/papers/KDD-2002-whatsthecode.pdf)
- [Programming Language Classifier (lazywei/mockingbird, GitHub)](https://github.com/lazywei/mockingbird)
